name: Node.js CI, Build, and Push to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-publish-image:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: a-very-secret-key-for-ci
          NODE_ENV: test
      
      - name: Azure Login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: azure/login@v1 # Use v1 as it's widely used and stable
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # enable-AzPSSession: true # Might be useful for some PS scripts later, not strictly for docker login

      - name: Log in to Azure Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: azure/docker-login@v2 # Use v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          # NO explicit credentials here. This action should now use the Azure session
          # established by the 'Azure Login' step above.
          # If this still fails, we might need to ensure the SP used by azure/login@v1
          # has an explicit "AcrPush" role assignment on the ACR. (It should already from our SP creation).

      - name: Build and tag Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:latest .
          echo "Image tagged with SHA: ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:${{ github.sha }}"
          echo "Image tagged with latest: ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:latest"
      
      - name: Push Docker image to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:latest