name: Node.js CI, Build, and Push to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-publish-image:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        # Removed 'options' block for simplicity, as mongo:latest usually starts fine.
        # Health can be managed by Mongoose connection retries or test setup if needed.
    
    strategy:
      matrix:
        node-version: [20.x] # Corrected list format
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Added quotes for clarity/safety
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: a-very-secret-key-for-ci # Make sure this matches what your app might expect
          NODE_ENV: test # For consistency, if app or tests check it
          # DB_URI is determined by server.js logic using GITHUB_ACTIONS env var
      
      - name: Azure Login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Log in o Azure Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          # No 'credentials' here, assuming azure/login@v1 sets up Docker access to ACR
      
      - name: Build and tag Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:latest .
          echo "Image tagged with SHA: ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:${{ github.sha }}"
          echo "Image tagged with latest: ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:latest"
      
      - name: Push Docker image to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/node-azure-api:latest